### ISSUE TITLE
Crashed on Fedora 27 default wayland gnome-session

### ISSUE THREAD

**Issue by maci0** [flathub/org.DolphinEmu.dolphin-emu#6]
```
$ env|grep XDG_SESSION
XDG_SESSION_ID=18
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=gnome
```

Crashes with
```
$ flatpak run org.DolphinEmu.dolphin-emu/x86_64/stable
Gdk-Message: Unable to load sb_h_double_arrow from the cursor theme

(dolphin-emu:2): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
```

Boots up fine with
```
flatpak run --env=GDK_BACKEND=x11 org.DolphinEmu.dolphin-emu/x86_64/stable
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
```

**Comment by maci0** [comment]
```
$ flatpak run --devel --command=sh  org.DolphinEmu.dolphin-emu/x86_64/stable
sh-4.3$ dolphin-emu 
Gdk-Message: Unable to load sb_h_double_arrow from the cursor theme

(dolphin-emu:3): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
Aborted (core dumped)
sh-4.3$ gdb dolphin-emu 
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from dolphin-emu...(no debugging symbols found)...done.
(gdb) run
Starting program: /app/bin/dolphin-emu 
warning: Error disabling address space randomization: Operation not permitted
warning: File "/usr/lib/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib/libthread_db-1.0.so
line to your configuration file "/home/maci/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/maci/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
warning: File "/usr/lib/libstdc++.so.6.0.22-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
[New LWP 36]
bGdk-Message: Unable to load sb_h_double_arrow from the cursor theme
[New LWP 37]
[New LWP 38]
[New LWP 39]
[New LWP 40]
[New LWP 41]

(dolphin-emu:22): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window

Thread 1 "dolphin-emu" received signal SIGSEGV, Segmentation fault.
0x00007f393e2f650e in _XSend () from /lib/libX11.so.6
(gdb) bt
#0  0x00007f393e2f650e in _XSend () at /lib/libX11.so.6
#1  0x00007f393e2f6960 in _XFlush () at /lib/libX11.so.6
#2  0x00007f393e2f9505 in _XGetRequest () at /lib/libX11.so.6
#3  0x00007f393e2ecc5d in XQueryExtension () at /lib/libX11.so.6
#4  0x00007f393e2e07d2 in XInitExtension () at /lib/libX11.so.6
#5  0x00007f393e0aff3f in XextAddDisplay () at /lib/libXext.so.6
#6  0x00007f393d784d36 in  () at /lib/libXrandr.so.2
#7  0x00007f393d7853ea in XRRQueryVersion () at /lib/libXrandr.so.2
#8  0x00000000005a55d1 in  ()
#9  0x0000000000514794 in  ()
#10 0x0000000000571690 in  ()
#11 0x00007f393f528d32 in wxEntry(int&, wchar_t**) () at /app/lib/libwx_baseu-3.0.so.0
#12 0x000000000043ed48 in  ()
#13 0x0000003995220291 in __libc_start_main () at /lib/libc.so.6
#14 0x000000000045378a in _start ()
```
